name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0
      id: go

    - name: CI
      run: make ci

    - name: Build all artifacts
      run: make build-all

    - name: "Release gh release latest"
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest
        allowUpdates: true
        artifacts: "builds/*"
        bodyFile: "builds/buildout"
        token: ${{ secrets.GITHUB_TOKEN }}